@php
  $normal = $statusCounts['Normal'] ?? 0;
  $undernourished = $statusCounts['Undernourished'] ?? 0;
  $severe = $statusCounts['Severely Undernourished'] ?? 0;
  $noMeasurement = $statusCounts['No Measurement'] ?? 0;
  $percent = fn($value) => $totalStudents > 0 ? round(($value / $totalStudents) * 100, 1) : 0;
@endphp
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Nutrition Monitoring Report</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: Arial, sans-serif; color: #082858; margin: 28px; }
    .header { display: flex; justify-content: space-between; gap: 24px; align-items: flex-start; border-bottom: 2px solid #0b3b82; padding-bottom: 16px; margin-bottom: 18px; }
    h1 { font-size: 22px; margin: 0 0 6px; }
    h2 { font-size: 15px; margin: 22px 0 10px; }
    .muted { color: #60708f; font-size: 12px; line-height: 1.5; }
    .print-btn { border: 0; background: #0b3b82; color: #fff; border-radius: 7px; padding: 9px 14px; font-weight: 700; cursor: pointer; }
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 18px 0; }
    .metric { border: 1px solid #dbe3ef; border-radius: 8px; padding: 12px; min-height: 82px; }
    .label { color: #60708f; font-size: 12px; margin-bottom: 6px; }
    .value { font-size: 22px; font-weight: 800; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { text-align: left; background: #eef3f9; color: #42567e; }
    th, td { border: 1px solid #dbe3ef; padding: 8px; vertical-align: top; }
    @media print {
      body { margin: 16mm; }
      .print-btn { display: none; }
      .metric { break-inside: avoid; }
      table { page-break-inside: auto; }
      tr { page-break-inside: avoid; page-break-after: auto; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>Nutrition Monitoring Report</h1>
      <div class="muted">
        {{ $schoolName }}<br>
        SY {{ $schoolYear }} &middot; {{ $startDate->format('M j, Y') }} to {{ $endDate->format('M j, Y') }}<br>
        Generated by {{ $generatedBy }} on {{ $generatedAt->format('M j, Y g:i A') }}
      </div>
    </div>
    <button class="print-btn" onclick="window.print()">Print / Save PDF</button>
  </div>

  <div class="summary">
    <div class="metric"><div class="label">Total Students</div><div class="value">{{ number_format($totalStudents) }}</div></div>
    <div class="metric"><div class="label">Normal</div><div class="value">{{ number_format($normal) }}</div><div class="muted">{{ $percent($normal) }}%</div></div>
    <div class="metric"><div class="label">Undernourished</div><div class="value">{{ number_format($undernourished) }}</div><div class="muted">{{ $percent($undernourished) }}%</div></div>
    <div class="metric"><div class="label">Severely Undernourished</div><div class="value">{{ number_format($severe) }}</div><div class="muted">{{ $percent($severe) }}%</div></div>
    <div class="metric"><div class="label">No Measurement</div><div class="value">{{ number_format($noMeasurement) }}</div><div class="muted">{{ $percent($noMeasurement) }}%</div></div>
    <div class="metric"><div class="label">Screened This Period</div><div class="value">{{ number_format($screenedStudents) }}</div><div class="muted">{{ $percent($screenedStudents) }}%</div></div>
    <div class="metric"><div class="label">Meals Served</div><div class="value">{{ number_format($mealTotals['meals_served']) }}</div><div class="muted">{{ number_format($mealTotals['avg_calories']) }} avg kcal</div></div>
    <div class="metric"><div class="label">Protein Served</div><div class="value">{{ number_format($mealTotals['protein_g'], 1) }}g</div><div class="muted">{{ number_format($mealTotals['avg_protein_g'], 1) }}g avg per meal</div></div>
  </div>

  <h2>Student Detail</h2>
  <table>
    <thead>
      <tr>
        <th>Student</th>
        <th>Grade / Section</th>
        <th>Status</th>
        <th>Latest Measurement</th>
        <th>BMI</th>
        <th>Meals</th>
        <th>Calories</th>
        <th>Protein</th>
      </tr>
    </thead>
    <tbody>
      @forelse($reportRows as $row)
        <tr>
          <td>{{ $row['student']->name }}</td>
          <td>{{ $row['student']->class_name ?? 'Unassigned' }} / {{ $row['student']->section ?? 'No section' }}</td>
          <td>{{ $row['status'] }}</td>
          <td>{{ $row['measured_at'] ?? 'Not screened' }}</td>
          <td>{{ $row['bmi'] ?? 'No BMI' }}</td>
          <td>{{ number_format($row['meals_served']) }}</td>
          <td>{{ number_format($row['calories']) }}</td>
          <td>{{ number_format($row['protein_g'], 1) }}g</td>
        </tr>
      @empty
        <tr>
          <td colspan="8">No students match the selected report filters.</td>
        </tr>
      @endforelse
    </tbody>
  </table>
</body>
</html>
